### ISSUE TITLE
Option --include_pids doesn't work

### ISSUE THREAD

**Issue by antonjuls** [lokalise/lokalise-cli#3]
Hey. I'm trying to export locales and mix keys from two my projects, as I see in docs I should use `include_pids` option, but seems it doesn't work.

My command is:
`lokalise --token  TOKEN export PID_1 --type json --dest /opt/dest --include_pids PID_2`

What am I doing wrong??

**Comment by antonjuls** [comment]
UPD: I tried to do this using Postman and just request to api and it works as expected! So seems the issue is definitely in CLI tool or in options format.

**Comment by nickustinov** [comment]
Anton, the issue is resolved now.
