### ISSUE TITLE
x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by 808brinks** [lokalise/lokalise-cli#4]
Since this morning i've been getting the following error using this docker image: x509: failed to load system roots and no roots provided. 

Seems like there might be an issue with certificates?

**Comment by klaustopher** [comment]
Happens for me as well with the new docker image that was uploaded at 6:39 PM yesterday https://hub.docker.com/r/lokalise/lokalise-cli

Unfortunately there is no tag of the old version available, so there is no chance to fix this on our end. And all of our builds are failing. 

Can you please release a new version that includes correct certs for the container to talk to lokalise?

Also, maybe add some tests to prevent stuff like this in the future?

**Comment by klaustopher** [comment]
Until #5 is merged (or another fix was applied), you can use this image: https://hub.docker.com/r/klaustopher/lokalise-cli-fixed

**DISCLAIMER**: This will be removed as soon as the main image is fixed, so please use at your own discretion 📦

**Comment by nickustinov** [comment]
We've pushed the corrected Dockerfile, it should be ready in 20-30 minutes depending on DockerHub load.
